### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by flapy2b** [biblibre/omeka-plugin-ItemDuplicateCheck#2]
Hi,
I have an installation error with Omeka 2.7 : 

`Zend_Db_Statement_Mysqli_Exception: Mysqli statement execute error : Can't create table `omeka_db`.`omeka_item_duplicate_check_rules` (errno: 150 "Foreign key constraint is incorrectly formed") in /var/www/html/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/html/omeka/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/html/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/html/omeka/application/libraries/Omeka/Db.php(80): Zend_Db_Adapter_Abstract->query('\n            CR...')
#3 /var/www/html/omeka/plugins/ItemDuplicateCheck/ItemDuplicateCheckPlugin.php(29): Omeka_Db->__call('query', Array)
#4 /var/www/html/omeka/application/libraries/Omeka/Plugin/Broker.php(142): ItemDuplicateCheckPlugin->hookInstall(Array)
#5 /var/www/html/omeka/application/libraries/Omeka/Plugin/Installer.php(126): Omeka_Plugin_Broker->callHook('install', Array, Object(Plugin))
#6 /var/www/html/omeka/application/controllers/PluginsController.php(95): Omeka_Plugin_Installer->install(Object(Plugin))
#7 /var/www/html/omeka/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction()
#8 /var/www/html/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction')
#9 /var/www/html/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /var/www/html/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#11 /var/www/html/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#12 /var/www/html/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#13 /var/www/html/omeka/admin/index.php(28): Omeka_Application->run()
#14 {main}`

I work with the last versions of Apache, PHP and MariaDB.

**Comment by DBinaghi** [comment]
See https://stackoverflow.com/questions/8434518/mysql-foreign-key-constraint-is-incorrectly-formed-error for help.
